### PR TITLE
Get dependencies and build correctly with ant

### PR DESCRIPTION
**Pull request by KewlCat**
Now *this* compiles properly with ant. It first gets the necessary dependencies (the most up-to-date where possible) and compiles to the correct location (target/jmeld.jar)
I need more time to tinker with ivy.

### CODE REVIEW

**Comment by albfan** [comment]
I will check compilation with jdk 1.5 to 1.8 and fix ivy dependencies. I will push it to master.

Seriously, I can't believe you think that dependency hell nigthmare is better than maven.

Until ant use ivy, add these to maven pom and you will get an accepted PR.

http://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven

**Comment by KewlCat** [comment]
Sorry I'm new to this. I did not intend to re-send the first changes, only the three latest ones. How do I create a partial pull request ? Should I rather generate and send patches ?

**Comment by albfan** [comment]
you can do this way:

    $ git branch keys b878586
    $ git rebase 710b0ef keys --onto e8027a^
    $ git push origin keys

then send a new PR from your new branch keys and add a reference to #23 on comments

Anyway I understand what you are trying to do, so I can cherry-pick changes accepted (you will keep on being author and committer) Let me know if you are comfortable with rebases and cherry-picking

https://git-scm.com/book/es/v2/Git-Tools-Rewriting-History

**Comment by albfan** [comment]
I have cherry-pick shorcuts to a new branch  https://github.com/albfan/jmeld/tree/shorcuts

Work about this will be managed on https://github.com/albfan/jmeld/issues/29

**Comment by albfan** [comment]
The shallow clone from jedit 

https://github.com/albfan/jEdit/

also is build with ant and ivy, so I guess it would be useful to review that project to add ivy to jmeld ant compilation

**Comment by albfan** [comment]
I'm resurrecting ant compilation (on branch ant) I want to compile with java 1.5 if it's possible. At this time that don't work.

Note (I have added gradle compilation with uber jar in 5 minutes)

For different features please open different PR

**Pull request closed without merging**
